/* ============================================================================
   POST-BUILD ROUTE GENERATOR

   GitHub Pages serves static files only — it has no server-side rewriting, so
   a request for /services/ is a 404 unless a real file exists at
   dist/services/index.html. That is why this script exists: it takes the one
   app shell Vite built (dist/index.html) and writes a real copy of it at
   every route in routes.js, each with its own <title>, description, canonical
   and social tags.

   The result: every URL returns a genuine HTTP 200 with the full live app —
   no hash fragments, no redirect stubs, nothing for a crawler to skip.

   This runs AFTER `vite build` (see package.json). It depends on Vite having
   been configured with base:'/' so the asset URLs inside index.html are
   absolute and therefore resolve correctly from any directory depth.
   ========================================================================== */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { destinationsData, continentsData, POPULAR_CATEGORIES } from './packagesData.js';
import { buildRoutes, STANDALONE_ROUTES, canonicalUrl, normalisePath } from './routes.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(__dirname, 'dist');

/** Escapes a string for safe use inside a double-quoted HTML attribute. */
function attr(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Escapes a string for use as HTML text content (e.g. inside <title>). */
function text(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Rewrites the SEO-bearing tags in the built shell for one route.
 * Every replacement is anchored to the exact tag shape emitted by
 * index.html, and each is asserted to have actually matched — a silent
 * no-op here would ship 225 pages all claiming to be the homepage, which
 * is precisely the duplicate-content problem this work exists to fix.
 */
function applyMeta(html, route) {
  const url = canonicalUrl(route.path);
  const title = route.title;
  const description = route.description || '';

  const edits = [
    [/<title>[\s\S]*?<\/title>/, `<title>${text(title)}</title>`],
    [
      /<meta\s+name="description"\s+content="[\s\S]*?"\s*\/>/,
      `<meta name="description" content="${attr(description)}" />`
    ],
    [
      /<link\s+rel="canonical"\s+href="[^"]*"\s*\/>/,
      `<link rel="canonical" href="${attr(url)}" />`
    ],
    [
      /<meta\s+property="og:title"\s+content="[\s\S]*?"\s*\/>/,
      `<meta property="og:title" content="${attr(title)}" />`
    ],
    [
      /<meta\s+property="og:description"\s+content="[\s\S]*?"\s*\/>/,
      `<meta property="og:description" content="${attr(description)}" />`
    ],
    [
      /<meta\s+property="og:url"\s+content="[^"]*"\s*\/>/,
      `<meta property="og:url" content="${attr(url)}" />`
    ],
    [
      /<meta\s+name="twitter:title"\s+content="[\s\S]*?"\s*\/>/,
      `<meta name="twitter:title" content="${attr(title)}" />`
    ],
    [
      /<meta\s+name="twitter:description"\s+content="[\s\S]*?"\s*\/>/,
      `<meta name="twitter:description" content="${attr(description)}" />`
    ]
  ];

  let out = html;
  const failed = [];
  for (const [pattern, replacement] of edits) {
    if (!pattern.test(out)) {
      failed.push(String(pattern));
      continue;
    }
    out = out.replace(pattern, replacement);
  }

  if (failed.length) {
    throw new Error(
      `Route "/${normalisePath(route.path)}/" — these <head> tags did not match ` +
      `the built shell, so the page would have kept the homepage's metadata:\n  ` +
      failed.join('\n  ') +
      `\nThe tag shape in index.html probably changed; update the patterns in generate-routes.mjs.`
    );
  }

  return out;
}

function sitemapXml(paths) {
  const entry = (path) => {
    const clean = normalisePath(path);
    // Homepage first and highest; section pages above the long tail of
    // individual destination/package pages.
    const depth = clean ? clean.split('/').length : 0;
    let priority = '1.0';
    let freq = 'weekly';
    if (clean) {
      priority = depth === 1 ? '0.8' : '0.6';
      freq = clean.startsWith('packages/') ? 'monthly' : 'weekly';
    }
    return `  <url>\n    <loc>${canonicalUrl(clean)}</loc>\n    <changefreq>${freq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
  };

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by generate-routes.mjs — do not edit by hand; your changes would
  be overwritten on the next build. Routes come from routes.js, which is the
  single source of truth shared with the client-side router.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${paths.map(entry).join('\n')}
</urlset>
`;
}

async function main() {
  const shellPath = resolve(DIST, 'index.html');
  let shell;
  try {
    shell = await readFile(shellPath, 'utf8');
  } catch {
    throw new Error(`dist/index.html not found — run \`vite build\` before this script.`);
  }

  // Guard the base:'/' requirement. A relative asset path would resolve
  // against the route's own directory (/services/assets/...) and 404.
  if (/(src|href)="\.\/assets\//.test(shell)) {
    throw new Error(
      'dist/index.html references assets relatively ("./assets/..."). Generated ' +
      'pages live in subdirectories, so those URLs would 404. Set base:"/" in ' +
      'vite.config.js.'
    );
  }

  const routes = buildRoutes(destinationsData, continentsData, POPULAR_CATEGORIES);

  const seen = new Set();
  const duplicates = [];
  for (const route of routes) {
    const key = normalisePath(route.path);
    if (seen.has(key)) duplicates.push(key);
    seen.add(key);
  }
  if (duplicates.length) {
    throw new Error(`Duplicate route paths in routes.js: ${duplicates.join(', ')}`);
  }

  let written = 0;
  for (const route of routes) {
    const clean = normalisePath(route.path);
    if (!clean) continue; // homepage — Vite already wrote dist/index.html

    const outDir = resolve(DIST, clean);
    await mkdir(outDir, { recursive: true });
    await writeFile(resolve(outDir, 'index.html'), applyMeta(shell, route), 'utf8');
    written += 1;
  }

  // Patch the homepage's own canonical/meta too, so it stays consistent with
  // the manifest rather than whatever index.html happened to be committed with.
  const home = routes.find((r) => !normalisePath(r.path));
  if (home) await writeFile(shellPath, applyMeta(shell, home), 'utf8');

  const sitemapPaths = [
    ...routes.map((r) => r.path),
    ...STANDALONE_ROUTES.map((r) => r.path)
  ];
  await writeFile(resolve(DIST, 'sitemap.xml'), sitemapXml(sitemapPaths), 'utf8');

  console.log(
    `[generate-routes] wrote ${written} route pages + sitemap.xml ` +
    `(${sitemapPaths.length} URLs total)`
  );
}

main().catch((err) => {
  console.error('[generate-routes] FAILED:', err.message);
  process.exit(1);
});
